#!/bin/sh
# Run by Codespaces after starting

# Set zsh as default shell
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  sudo chsh -s /bin/zsh root
fi

# Default to signing git commits
git config --global commit.gpgsign true