#!/bin/sh
# Run by Codespaces after starting

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  chsh -s /bin/zsh root
fi

sudo apt install python3-dev python3-pip python3-setuptools
sudo pip3 install thefuck
