#!/bin/sh
# Run by Codespaces after starting

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  sudo chsh -s /bin/zsh root
fi

# Default to signing git commits
git config --global commit.gpgsign true
